"""PR-AV12 (AV-12) — generated-files ledger drift reconciler.

Closes AV-12 from the 5/14 EOD substrate backlog. The handoff said:

  AV-12 | Generated-files ledger drift (db_files missing entries that
       exist on disk) | Medium

`/api/rfq/<rid>/package-diag` already surfaces the drift: it returns
both `db_files` (rows in the rfq_files table) and `output_dir_files`
(literal `os.listdir` on data/output/<sol>). On records generated by
older code paths these don't agree — files exist on disk but never
got a ledger row inserted. Downstream consumers that enumerate via
`list_rfq_files` (Gmail draft attachments, file-download routes,
audit views) silently miss those files.

THE FIX

New `_reconcile_rfq_files_to_disk(rid, sol)` helper + admin route
`POST /api/admin/rfq/<rid>/reconcile-files` that:

  1. Walks the per-RFQ output directory
     (data/output/<sol> with rid fallback for legacy)
  2. Lists existing `rfq_files` ledger rows for this rid
  3. For each *.pdf on disk NOT in the ledger, reads bytes and
     calls `save_rfq_file(rid, filename, "pdf", data,
     category="generated", uploaded_by="reconcile")`

Idempotent: `save_rfq_file` dedups by (rfq_id, filename, category),
so re-running converges to the same state — no risk of inserting
duplicate rows.

Tests pin the contract without standing up the full DB:
  - Helper exists with the expected signature
  - Helper returns the standard shape (ok, added, files_added,
    skipped, errors)
  - No output directory → ok=False, no crash
  - Empty directory → ok=True, added=0
  - Disk-only PDFs are detected (when ledger comparison finds
    them missing)
  - Source-grep guards for the admin route + AV-12 marker
"""
from __future__ import annotations

import os
import pytest


def test_helper_signature_and_marker():
    """Source-grep: AV-12 marker present, helper exported."""
    import inspect
    from src.api.modules import routes_rfq_admin
    src = inspect.getsource(routes_rfq_admin)
    assert "PR-AV12" in src
    assert "_reconcile_rfq_files_to_disk" in src
    assert "api_admin_rfq_reconcile_files" in src


def test_helper_returns_standard_shape_when_no_output_dir(tmp_path,
                                                            monkeypatch):
    """When the output dir doesn't exist for the RFQ, helper returns
    ok=False with an error string — never crashes."""
    from src.api.modules.routes_rfq_admin import _reconcile_rfq_files_to_disk
    # Point DATA_DIR to a tmp path with no output subdirs
    from src.api.modules import routes_rfq_admin as _rra
    monkeypatch.setattr(_rra, "DATA_DIR", str(tmp_path))
    result = _reconcile_rfq_files_to_disk("rfq_nonexistent", "FAKE-SOL")
    assert result["ok"] is False
    assert result["added"] == 0
    assert result["files_added"] == []
    assert result["skipped"] == 0
    assert any("No output directory" in e for e in result["errors"])


def test_helper_no_op_when_directory_empty(tmp_path, monkeypatch):
    """When the directory exists but has no PDFs, helper returns
    ok=True with no additions and no errors."""
    from src.api.modules.routes_rfq_admin import _reconcile_rfq_files_to_disk

    sol = "EMPTY-SOL"
    out_dir = tmp_path / "output" / sol
    out_dir.mkdir(parents=True)
    from src.api.modules import routes_rfq_admin as _rra
    monkeypatch.setattr(_rra, "DATA_DIR", str(tmp_path))
    # Stub list_rfq_files to return empty so no ledger noise
    monkeypatch.setattr(
        "src.api.dashboard.list_rfq_files",
        lambda rid, category=None: [],
    )
    result = _reconcile_rfq_files_to_disk("rfq_x", sol)
    assert result["ok"] is True
    assert result["added"] == 0
    assert result["files_added"] == []
    assert result["errors"] == []


def test_helper_ignores_non_pdf_files(tmp_path, monkeypatch):
    """Manifest.json + audit.log live alongside PDFs but aren't
    consumer-facing attachments — they must NOT be added to
    rfq_files."""
    from src.api.modules.routes_rfq_admin import _reconcile_rfq_files_to_disk

    sol = "TEST-SOL"
    out_dir = tmp_path / "output" / sol
    out_dir.mkdir(parents=True)
    (out_dir / "manifest.json").write_text("{}")
    (out_dir / "audit.log").write_text("log")
    (out_dir / "notes.txt").write_text("ignore me")

    from src.api.modules import routes_rfq_admin as _rra
    monkeypatch.setattr(_rra, "DATA_DIR", str(tmp_path))
    monkeypatch.setattr(
        "src.api.dashboard.list_rfq_files",
        lambda rid, category=None: [],
    )
    # Spy on save_rfq_file — must NOT be called
    save_calls = []
    monkeypatch.setattr(
        "src.api.dashboard.save_rfq_file",
        lambda **kw: save_calls.append(kw) or "rf_test",
    )
    result = _reconcile_rfq_files_to_disk("rfq_x", sol)
    assert result["ok"] is True
    assert result["added"] == 0
    assert save_calls == []


def test_helper_adds_disk_only_pdfs(tmp_path, monkeypatch):
    """The substrate fix: PDFs on disk but not in the ledger get
    save_rfq_file invocations."""
    from src.api.modules.routes_rfq_admin import _reconcile_rfq_files_to_disk

    sol = "PREQ-TEST"
    out_dir = tmp_path / "output" / sol
    out_dir.mkdir(parents=True)
    (out_dir / "10847262_703C_Reytech.pdf").write_bytes(b"%PDF-fake-1")
    (out_dir / "10847262_704B_Reytech.pdf").write_bytes(b"%PDF-fake-2")
    (out_dir / "10847262_BidPackage_Reytech.pdf").write_bytes(b"%PDF-fake-3")

    from src.api.modules import routes_rfq_admin as _rra
    monkeypatch.setattr(_rra, "DATA_DIR", str(tmp_path))
    # Empty ledger — all 3 disk files are "drift"
    monkeypatch.setattr(
        "src.api.dashboard.list_rfq_files",
        lambda rid, category=None: [],
    )
    save_calls = []
    monkeypatch.setattr(
        "src.api.dashboard.save_rfq_file",
        lambda **kw: save_calls.append(kw) or "rf_test",
    )

    result = _reconcile_rfq_files_to_disk("rfq_test", sol)
    assert result["ok"] is True
    assert result["added"] == 3
    assert set(result["files_added"]) == {
        "10847262_703C_Reytech.pdf",
        "10847262_704B_Reytech.pdf",
        "10847262_BidPackage_Reytech.pdf",
    }
    assert len(save_calls) == 3
    # All inserts use category="generated" (operator can distinguish
    # ledger-reconciled rows from original-ingest buyer_attachments)
    for call in save_calls:
        assert call.get("category") == "generated"
        assert call.get("uploaded_by") == "reconcile"
        assert call.get("file_type") == "pdf"


def test_helper_skips_ledger_matches(tmp_path, monkeypatch):
    """When a disk file already has a ledger entry (filename match,
    case-insensitive), it's counted in `skipped`, not `added`."""
    from src.api.modules.routes_rfq_admin import _reconcile_rfq_files_to_disk

    sol = "TEST-SOL"
    out_dir = tmp_path / "output" / sol
    out_dir.mkdir(parents=True)
    (out_dir / "OnLedger.pdf").write_bytes(b"%PDF-1")
    (out_dir / "OffLedger.pdf").write_bytes(b"%PDF-2")

    from src.api.modules import routes_rfq_admin as _rra
    monkeypatch.setattr(_rra, "DATA_DIR", str(tmp_path))
    # Ledger has one of the two files (case-different to test
    # case-insensitive comparison)
    monkeypatch.setattr(
        "src.api.dashboard.list_rfq_files",
        lambda rid, category=None: [
            {"id": "rf_existing", "filename": "onledger.pdf"},
        ],
    )
    save_calls = []
    monkeypatch.setattr(
        "src.api.dashboard.save_rfq_file",
        lambda **kw: save_calls.append(kw) or "rf_new",
    )

    result = _reconcile_rfq_files_to_disk("rfq_x", sol)
    assert result["added"] == 1
    assert result["skipped"] == 1
    assert result["files_added"] == ["OffLedger.pdf"]


def test_helper_handles_empty_pdf_gracefully(tmp_path, monkeypatch):
    """A zero-byte PDF on disk → logged error, not silent insert."""
    from src.api.modules.routes_rfq_admin import _reconcile_rfq_files_to_disk

    sol = "TEST-SOL"
    out_dir = tmp_path / "output" / sol
    out_dir.mkdir(parents=True)
    (out_dir / "empty.pdf").write_bytes(b"")  # 0 bytes

    from src.api.modules import routes_rfq_admin as _rra
    monkeypatch.setattr(_rra, "DATA_DIR", str(tmp_path))
    monkeypatch.setattr(
        "src.api.dashboard.list_rfq_files",
        lambda rid, category=None: [],
    )
    save_calls = []
    monkeypatch.setattr(
        "src.api.dashboard.save_rfq_file",
        lambda **kw: save_calls.append(kw) or "rf_new",
    )

    result = _reconcile_rfq_files_to_disk("rfq_x", sol)
    assert result["added"] == 0
    assert save_calls == []
    assert any("empty file" in e for e in result["errors"])


def test_helper_falls_back_to_rid_directory(tmp_path, monkeypatch):
    """Legacy records used the record_id as the output directory
    name. When sol-based path doesn't exist, fall back to rid-based."""
    from src.api.modules.routes_rfq_admin import _reconcile_rfq_files_to_disk

    rid = "rfq_legacy_abc"
    out_dir = tmp_path / "output" / rid
    out_dir.mkdir(parents=True)
    (out_dir / "Quote.pdf").write_bytes(b"%PDF-x")

    from src.api.modules import routes_rfq_admin as _rra
    monkeypatch.setattr(_rra, "DATA_DIR", str(tmp_path))
    monkeypatch.setattr(
        "src.api.dashboard.list_rfq_files",
        lambda rid_, category=None: [],
    )
    save_calls = []
    monkeypatch.setattr(
        "src.api.dashboard.save_rfq_file",
        lambda **kw: save_calls.append(kw) or "rf_new",
    )

    # Pass an empty sol — should fall back to rid dir
    result = _reconcile_rfq_files_to_disk(rid, sol="")
    assert result["ok"] is True
    assert result["added"] == 1
    assert "Quote.pdf" in result["files_added"]


def test_admin_route_returns_404_for_missing_rfq(monkeypatch):
    """The route handler must reject unknown rid with 404, not crash
    when the helper tries to compute sol from a missing record."""
    import inspect
    from src.api.modules import routes_rfq_admin
    src = inspect.getsource(routes_rfq_admin.api_admin_rfq_reconcile_files)
    # Look for the not-found guard
    assert "RFQ not found" in src
    assert "404" in src
