"""Package completeness gate — agency-agnostic hard fail.

PR D: Gives every agency the same "100% of the time every time"
guarantee that the CCHCS packet got in PR #40. After generate_rfq_package
runs through every filler, this gate verifies that:

  1. Every form in agency_config.required_forms is present in
     output_files (generation completeness)
  2. Every required form that IS present passes form_qa (quality
     completeness)

Any gap in either dimension flips the package to `generated_incomplete`
status, which:
  - Blocks the draft email from being created
  - Shows an error banner on the review page
  - Logs a lifecycle event with exact missing/failed form list
  - Prevents the operator from accidentally sending an incomplete
    package to a buyer

Usage:
    from src.forms.package_completeness import check_package_completeness
    result = check_package_completeness(
        required_forms={"quote", "dvbe843", "cv012_cuf", ...},
        generated_form_ids={"quote", "dvbe843"},  # from output_files
        qa_form_results={"dvbe843": {"passed": True}, ...},
    )
    if not result["complete"]:
        # block send, flash error, etc.
        print(result["reasons"])
"""
from __future__ import annotations

from typing import Any, Dict, Iterable, List, Set

# Forms that are CONTENT-TRIGGERED (not agency-required) and never
# block a send if missing even if they show up in some agency's
# required_forms list. These are auto-generated by the dispatcher
# based on RFQ content (food items → OBS 1600) or facility detection
# (Barstow → barstow_cuf), not by agency policy.
#
# Do NOT add forms here just because they're "usually optional".
# std205 / std1000 / drug_free are AGENCY-REQUIRED for some agencies
# (CalVet requires all three) so they must block when missing.
NON_BLOCKING_FORMS: Set[str] = {
    "obs_1600",       # food items only — content-triggered
    "barstow_cuf",    # Barstow facility only — location-triggered
}


def check_package_completeness(
    required_forms: Iterable[str],
    generated_form_ids: Iterable[str],
    qa_form_results: Dict[str, Dict[str, Any]] | None = None,
    non_blocking_forms: Set[str] = None,
) -> Dict[str, Any]:
    """Return a completeness report.

    Args:
        required_forms: set of form_ids the agency requires (from
            agency_config.required_forms)
        generated_form_ids: set of form_ids that actually ended up
            in output_files (from _gen_forms)
        qa_form_results: form_qa.run_form_qa() result["form_results"]
            dict, used to detect required forms that generated but
            failed QA
        non_blocking_forms: override the default NON_BLOCKING_FORMS set
            (primarily for tests)

    Returns: {
        "complete": bool,
        "reasons": [str],            # human-readable per-issue
        "missing_required": [str],   # forms in required not in generated
        "failed_required": [str],    # forms in required that failed QA
        "missing_count": int,
        "failed_count": int,
    }

    A package is `complete` iff:
      - Every required form (minus non_blocking_forms) is in
        generated_form_ids
      - Every required form that IS present passed QA (or had no
        QA result at all, which is a non-blocking warning)
    """
    required = set(required_forms or [])
    generated = set(generated_form_ids or [])
    qa_results = qa_form_results or {}
    non_blocking = non_blocking_forms if non_blocking_forms is not None else NON_BLOCKING_FORMS

    # Missing: in required, not in generated, not in non_blocking
    missing = sorted(
        f for f in required
        if f not in generated and f not in non_blocking
    )

    # Failed: in required and in generated but QA says failed
    failed = sorted(
        f for f in required
        if f in generated
        and qa_results.get(f, {}).get("passed", True) is False
    )

    reasons: List[str] = []
    if missing:
        reasons.append(
            f"missing required forms: {', '.join(missing)}"
        )
    if failed:
        reasons.append(
            f"required forms failed QA: {', '.join(failed)}"
        )

    return {
        "complete": not reasons,
        "reasons": reasons,
        "missing_required": missing,
        "failed_required": failed,
        "missing_count": len(missing),
        "failed_count": len(failed),
    }


__all__ = [
    "check_package_completeness",
    "NON_BLOCKING_FORMS",
]
