"""Package completeness gate — agency-agnostic hard fail.

PR D: Gives every agency the same "100% of the time every time"
guarantee that the CCHCS packet got in PR #40. After generate_rfq_package
runs through every filler, this gate verifies that:

  1. Every form in agency_config.required_forms is present in
     output_files (generation completeness)
  2. Every required form that IS present passes form_qa (quality
     completeness)

Any gap in either dimension flips the package to `generated_incomplete`
status, which:
  - Blocks the draft email from being created
  - Shows an error banner on the review page
  - Logs a lifecycle event with exact missing/failed form list
  - Prevents the operator from accidentally sending an incomplete
    package to a buyer

Usage:
    from src.forms.package_completeness import check_package_completeness
    result = check_package_completeness(
        required_forms={"quote", "dvbe843", "cv012_cuf", ...},
        generated_form_ids={"quote", "dvbe843"},  # from output_files
        qa_form_results={"dvbe843": {"passed": True}, ...},
    )
    if not result["complete"]:
        # block send, flash error, etc.
        print(result["reasons"])
"""
from __future__ import annotations

from typing import Any, Dict, Iterable, List, Set

# Forms that are CONTENT-TRIGGERED (not agency-required) and never
# block a send if missing even if they show up in some agency's
# required_forms list. These are auto-generated by the dispatcher
# based on RFQ content (food items → OBS 1600) or facility detection
# (Barstow → barstow_cuf), not by agency policy.
#
# Do NOT add forms here just because they're "usually optional".
# std205 / std1000 / drug_free are AGENCY-REQUIRED for some agencies
# (CalVet requires all three) so they must block when missing.
NON_BLOCKING_FORMS: Set[str] = {
    "obs_1600",       # food items only — content-triggered
    "barstow_cuf",    # Barstow facility only — location-triggered
}


# AV-11 (2026-05-14): form-pair substitution. When a required form is
# missing but a documented substitute IS generated, treat the
# requirement as satisfied.
#
# Use case that drove this: CCHCS agency_config lists `required_forms`
# = ["703b", "704b", "bidpkg", "quote"]. The buyer sometimes ships a
# 703C ("Fair and Reasonable / Exempt — Price Request") instead of
# 703B. The package generator at routes_rfq_gen.py:2092 already
# selects 703C when the buyer uploaded it (the filename is
# `<sol>_703C_Reytech.pdf`). Without substitution, this gate marks
# "703b" missing → blocks send.
#
# Symmetric: an agency that ever demands 703C is satisfied by a 703B.
# Both forms occupy the same "buyer-line-item-pricing" slot in
# AMS-style packages.
#
# Conservative scope: only ADD known pairs Mike has explicitly
# accepted. Don't generalize to "any optional form satisfies any
# required form" — that would silently hide real gaps.
ACCEPTS_SUBSTITUTE: Dict[str, Set[str]] = {
    "703b": {"703c"},   # 703C is the "fair-and-reasonable" variant
    "703c": {"703b"},   # symmetric — an agency demanding 703C is
                        # satisfied by a 703B fill
}


def check_package_completeness(
    required_forms: Iterable[str],
    generated_form_ids: Iterable[str],
    qa_form_results: Dict[str, Dict[str, Any]] | None = None,
    non_blocking_forms: Set[str] = None,
    accepts_substitute: Dict[str, Set[str]] = None,
) -> Dict[str, Any]:
    """Return a completeness report.

    Args:
        required_forms: set of form_ids the agency requires (from
            agency_config.required_forms)
        generated_form_ids: set of form_ids that actually ended up
            in output_files (from _gen_forms)
        qa_form_results: form_qa.run_form_qa() result["form_results"]
            dict, used to detect required forms that generated but
            failed QA
        non_blocking_forms: override the default NON_BLOCKING_FORMS set
            (primarily for tests)

    Returns: {
        "complete": bool,
        "reasons": [str],            # human-readable per-issue
        "missing_required": [str],   # forms in required not in generated
        "failed_required": [str],    # forms in required that failed QA
        "missing_count": int,
        "failed_count": int,
    }

    A package is `complete` iff:
      - Every required form (minus non_blocking_forms) is in
        generated_form_ids
      - Every required form that IS present passed QA (or had no
        QA result at all, which is a non-blocking warning)
    """
    required = set(required_forms or [])
    generated = set(generated_form_ids or [])
    qa_results = qa_form_results or {}
    non_blocking = non_blocking_forms if non_blocking_forms is not None else NON_BLOCKING_FORMS
    sub_map = accepts_substitute if accepts_substitute is not None else ACCEPTS_SUBSTITUTE

    # AV-11: a required form is satisfied if it OR any documented
    # substitute is in generated. Build per-form satisfier set.
    def _satisfied(form_id: str) -> bool:
        if form_id in generated:
            return True
        for sub in (sub_map.get(form_id) or ()):
            if sub in generated:
                return True
        return False

    # Track which substitutes filled which slots — surfaces on the
    # response so callers (UI banner, QA log) can show "703B satisfied
    # by 703C buyer attachment" instead of an opaque green check.
    substituted: Dict[str, str] = {}
    for f in required:
        if f in generated or f in non_blocking:
            continue
        for sub in (sub_map.get(f) or ()):
            if sub in generated:
                substituted[f] = sub
                break

    # Missing: in required, NOT satisfied (directly or via substitute),
    # and not in non_blocking.
    missing = sorted(
        f for f in required
        if not _satisfied(f) and f not in non_blocking
    )

    # Failed: in required and EITHER itself or its substitute is in
    # generated but the QA result for whichever is generated says
    # failed.
    failed: List[str] = []
    for f in required:
        candidates = {f} | set(sub_map.get(f) or ())
        present = [c for c in candidates if c in generated]
        if not present:
            continue
        if all(qa_results.get(c, {}).get("passed", True) is False
               for c in present):
            failed.append(f)
    failed = sorted(failed)

    reasons: List[str] = []
    if missing:
        reasons.append(
            f"missing required forms: {', '.join(missing)}"
        )
    if failed:
        reasons.append(
            f"required forms failed QA: {', '.join(failed)}"
        )

    return {
        "complete": not reasons,
        "reasons": reasons,
        "missing_required": missing,
        "failed_required": failed,
        "missing_count": len(missing),
        "failed_count": len(failed),
        "substituted": substituted,
    }


__all__ = [
    "check_package_completeness",
    "NON_BLOCKING_FORMS",
    "ACCEPTS_SUBSTITUTE",
]
